apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  
  postsubmits:
  - name: devbranch
    context: "devbranch"
    source: "devbranch.yaml"
    ignore_changes: "OWNERS"
    branches:
    - ^dev$
  - name: release
    context: "release"
    source: "release.yaml"
    ignore_changes: "OWNERS"
    branches:
    - ^dev$
    - ^ci/1201976550272266_add-into-jx-cluster$
    - ^main$
    - ^master$
