apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: false
    optional: false
    source: "pullrequest.yaml"
    ignore_changes: "OWNERS"
  postsubmits:
  - name: devbranch
    context: "devbranch"
    source: "devbranch.yaml"
    ignore_changes: "OWNERS"
    branches:
    - ^dev$
  - name: release
    context: "release"
    source: "release.yaml"
    ignore_changes: "OWNERS"
    branches:
    - ^dev-testrelease$
    - ^main$
    - ^master$
