apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: false
    optional: false
    source: "pullrequest.yaml"
    ignore_changes: "OWNERS"
  postsubmits:
  - name: demo
    context: "demo"
    source: "demo.yaml"
    ignore_changes: "OWNERS"
    branches:
    - ^demo-p2p-server$
  - name: release
    context: "release"
    source: "release.yaml"
    ignore_changes: "OWNERS"
    branches:
    - ^dev$
    - ^main$
    - ^master$